# Generated by Django 3.0.5 on 2020-04-10 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=100, verbose_name='Название способности')),
                ('ability_cooldown', models.CharField(max_length=100, verbose_name='Перезарядка способности')),
                ('ability_damage', models.CharField(max_length=100, verbose_name='Урон способности')),
                ('ability_description', models.CharField(max_length=10000, verbose_name='Описание способности')),
            ],
            options={
                'verbose_name': 'Способность',
                'verbose_name_plural': 'Способности',
            },
        ),
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Матерные слова')),
            ],
            options={
                'verbose_name': 'Матерное слово',
                'verbose_name_plural': 'Матерные слова',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('item_description', models.CharField(max_length=10000, verbose_name='Описание предмета')),
                ('item_stats', models.CharField(max_length=10000, verbose_name='Характеристики предмета')),
                ('item_cooldown', models.CharField(max_length=10000, verbose_name='Перезарядка предмета')),
                ('item_image', models.CharField(max_length=200, verbose_name='Изображение предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='NoBadWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Исключения')),
            ],
            options={
                'verbose_name': 'Исключение',
                'verbose_name_plural': 'Исключения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_name', models.CharField(max_length=100, verbose_name='Название руны')),
                ('rune_description', models.CharField(max_length=10000, verbose_name='Описание руны')),
                ('rune_cooldown', models.CharField(max_length=10000, verbose_name='Перезарядка руны')),
                ('rune_image', models.CharField(max_length=200, verbose_name='Изображение руны')),
            ],
            options={
                'verbose_name': 'Руна',
                'verbose_name_plural': 'Руны',
            },
        ),
        migrations.CreateModel(
            name='SectionNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_news_name', models.CharField(max_length=100, verbose_name='Название раздела новостей')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='SectionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_topic_name', models.CharField(max_length=100, verbose_name='Название раздела тем')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, verbose_name='Название Темы')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('topic_text', models.CharField(max_length=1000, verbose_name='Исходный текст')),
                ('edit_topic_text', models.CharField(max_length=1000, verbose_name='Отредактированный текст')),
                ('ip_user', models.CharField(blank=True, max_length=100, verbose_name='ip address')),
                ('topic_section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.SectionTopic', verbose_name='Раздел')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=100, verbose_name='Название новости')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('news_text', models.CharField(max_length=1000, verbose_name='Исходный текст')),
                ('edit_news_text', models.CharField(max_length=1000, verbose_name='Отредактированный текст')),
                ('ip_user', models.CharField(blank=True, max_length=100, verbose_name='ip address')),
                ('news_section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.SectionNews', verbose_name='Раздел')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=100, verbose_name='Название Чемпиона')),
                ('rune_description', models.CharField(max_length=10000, verbose_name='Описание Чемпиона')),
                ('rune_image', models.CharField(max_length=200, verbose_name='Изображение Чемпиона')),
                ('champion_hp', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('champion_mp', models.CharField(max_length=100, verbose_name='Мана')),
                ('champion_speed', models.CharField(max_length=100, verbose_name='Скорость')),
                ('champion_attack_speed', models.CharField(max_length=100, verbose_name='Скорость атаки')),
                ('champion_armor', models.CharField(max_length=100, verbose_name='Броня')),
                ('champion_resist', models.CharField(max_length=100, verbose_name='Сопротивление магии')),
                ('champion_damage', models.CharField(max_length=100, verbose_name='Урон')),
                ('champion_ability', models.ManyToManyField(to='polls.Ability', verbose_name='Специальности')),
            ],
            options={
                'verbose_name': 'Чемпион',
                'verbose_name_plural': 'Чемпионы',
            },
        ),
    ]
