# Generated by Django 3.0.5 on 2020-04-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionnews',
            options={'verbose_name': 'Раздел Новости', 'verbose_name_plural': 'Разделы Новости'},
        ),
        migrations.AlterModelOptions(
            name='sectiontopic',
            options={'verbose_name': 'Раздел Темы', 'verbose_name_plural': 'Разделы Тем'},
        ),
    ]
